### ISSUE TITLE
Please provide SPDX files in JSON / YAML format

### ISSUE THREAD

**Issue by sschuberth** [Open-Source-Compliance/package-analysis#20]
SPDX tag-value format (as well as RDF) is more or less legacy, and tools like [ORT](https://github.com/oss-review-toolkit/ort) do not even bother to support these formats anymore in favor of only supporting JSON / YAML instead. Esp. YAML also offers a good compromise between being both machine- and human-readable.

I know that we could leverage [SPDX tools](https://github.com/spdx/tools) to do any format conversion on the client side, but I feel it makes more sense to do the conversion once centrally (this project is looking to share results by avoiding everyone to do the same work again after all).

While SPDX tag-value maybe cannot be replaced, providing JSON / YAML additionally would be appreciated.

/cc @heliocastro

**Comment by infojg9** [comment]
+1 to @heliocastro for focusing future readiness of SBOM.

Perhaps https://github.com/spdx/spdx-java-jackson-store or https://github.com/anthonyharrison/sbom-manager or https://github.com/CycloneDX/cyclonedx-javascript-library can be extended as plugin for JSON/YAML adaptation?

Question: How about CycloneDX capability?

/cc @maxbrito @infojg9

**Comment by heliocastro** [comment]
This could be solved in a fashionable way using CI.
The produced document could be in format yaml or json, and when commited to the repository, just run the spdx-tool conversion  to generate the tag format, and commit it on the repo

**Comment by OliverFendt** [comment]
@sschuberth thank you for the proposal, if this will broaden the use and adoption we will provide those formats too.
@heliocastro good idea, would you like to contribute such a script for CI for me currently the converter from TV to json/yaml is more urgent

**Comment by sschuberth** [comment]
> for CI for me currently the converter from TV to json/yaml is more urgent

You could also implement @heliocastro's proposal the opposite way: A CI bot that converts tag-value to YAML / JSON. That same logic could then be used to both convert the current files, and convert any future files being contributed.

**Comment by OliverFendt** [comment]
@sschuberth perhaps you want to look at https://github.com/Open-Source-Compliance/package-analysis/tree/main/analysed-packages/boost/version-1.81.0 is this what you can integrate?

**Comment by sschuberth** [comment]
Yes, that looks good from a quick glance.

**Comment by hex3262** [comment]
I just tried an experimental SPDX to JSON converter I wrote, but I'm not sure if the new files are usable. Could you have alook? The files are on a commit without PR: https://github.com/Open-Source-Compliance/package-analysis/commit/34b51acd3550cdf4c40c5b28990ce0f8d92a63c9

**Comment by heliocastro** [comment]
Hey @hex3262 
Was a nice try but we should use the official tooling, that already do that for us.
I just sent a pull request executing this process, but will only act if the verify step pass.
@sschuberth I was thinking same as you, to act only on new commits.  Can i have a shot ?

**Comment by sschuberth** [comment]
> Can i have a shot ?

From my perspective, sure, I'm on vacation currently anyway 😊

**Comment by heliocastro** [comment]
@OliverFendt This issue can be closed with last merged commit.
Thanks

**Comment by OliverFendt** [comment]
Thank you all for working on this issue.
