### ISSUE TITLE
Currently, one file does not validate

### ISSUE THREAD

**Issue by maxhbr** [Open-Source-Compliance/package-analysis#45]
Found via CI:

```
Verify analysed-packages/linux/version-6.1.21/linux-6.1.21-SPDX2TV.spdx
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
This SPDX Document is not valid due to:
        Duplicate extracted license ID: LicenseRef-GFDL-1.1-or-later
 ```

**Comment by OliverFendt** [comment]
@maxhbr thank you for spotting this, I will look into

**Comment by OliverFendt** [comment]
I checked it, indeed there were to GFDL-1.1-or-later licenseIDs. As far as I was able to check the license texts, they were equal, not looking at the different line breaks. I removed one. For the files with GFDL-1.1-or-later as concluded license or license info in file this has no impact.
