### ISSUE TITLE
libunistring 1.0 missing SPDX files

### ISSUE THREAD

**Issue by Jasper-Ben** [Open-Source-Compliance/package-analysis#65]
libunistring 1.0 is missing SPDX files, causing unexpected behavior when using the REST API to retrieve the associated files for this package

**Comment by OliverFendt** [comment]
Good catch @Jasper-Ben, I work on this, it might be that it will take some days. Thank you for spotting this.

**Comment by OliverFendt** [comment]
I added libunistring-1.0-SPDX2TV.spdx and updated the OSS-disclosure document. @Jasper-Ben can you please check the behavior of the REST API, if everything is ok I will close the issue
