### ISSUE TITLE
Source code differences between github "archive" and "releases"

### ISSUE THREAD

**Issue by Jasper-Ben** [Open-Source-Compliance/package-analysis#67]
While integrating osselot into Yocto build I noticed a reoccurring pattern of missing license information for `configure` generated data.

For example, see the following output for libexpat and libffi (notice the `spdx_checksum_data_missing` key):

[expat-package-meta.json](https://github.com/Open-Source-Compliance/package-analysis/files/13928222/package-meta.json)
[libffi-package-meta.json](https://github.com/Open-Source-Compliance/package-analysis/files/13928244/package-meta.json)

I noticed that this is due to Yocto using the following links for downloading the respective packages:

https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz
https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2

while the osselot data was created from the following links:

https://github.com/libffi/libffi/archive/refs/tags/v3.4.4.tar.gz
https://github.com/libexpat/libexpat/archive/refs/tags/R_2_5_0.tar.gz

These links correspond to the following respectively:
![image](https://github.com/Open-Source-Compliance/package-analysis/assets/12223583/6908dbab-34c7-4411-ba65-b81b472f33da)

Since running the `configure` step ist required for doing a successful build (I believe this step should not affect pre-existing files?), I am wondering if it would make sense to use the "release" downloads as the data basis for the osselot curation, rather then the source code archives?
Having more data available does not hurt (again: assuming the configure step does not modify existing data, needs verification) when using the "archive" download, however having data left to clear when using the "release" download is an inconvenience.

**Comment by OliverFendt** [comment]
@Jasper-Ben thank you very much for reporting this. Indeed the packages are different. I will provide the analysis results of the two "release packages" in the next couple of days. I'm wondering how to provide them - a different set of artifacts with a different name, or simply exchanging the content of the existing version directories, I have to admit that this is not my preferred solution, do you have any good suggestion?
In general this means that we shall use the "release packages" in future, or?

**Comment by Jasper-Ben** [comment]
@OliverFendt I am not 100% sure yet how (and if at all) we should address this, for now I just wanted to make you aware of this issue.

I am not too familiar with the whole configure process, so I'll take a closer look into what these scripts actually do. From my limited understanding so far the configure script also does machine specific configuration, so I am actually quite surprised that

a) these are shipped within the release links to begin with
b) these are used by the Yocto project (although they are probably re-configured during the yocto build process if the [autotools](https://docs.yoctoproject.org/singleindex.html#autotools) class is inherited)

The "correct" fix in this case might also be that Yocto should use the "archive" instead of the "release" artifacts. However, this would probably mean a lot¹ of recipe changes in Yocto would be required. This is due to the fact that while most recipes respect the variable `GITHUB_BASE_URI=https://github.com/${BPN}/${BPN}/releases/"` which could be adjusted globally, all source checksums would fail due to the change in artifact.

Regardless of the Yocto use-case it might still make sense to clear the release packages. Regarding your question, whether this should happen in a separate curation artifact or within the pre-existing curation IMO depends on whether there is the (the slightest) possibility of the configuration script modifying existing files. If this question can be confidently answered with "no", I do not see the harm of adding them into the existing curations. 

---

¹: Actually, it aren't *too* many cases (23), so adjusting this would be doable, if this doesn't have any other negative impact I am unaware of:

```bash
grep -rE "GITHUB_BASE_URI\s*=" poky meta-openembedded | grep ".bb" | wc -l 
23
```

I will try to get a third opinion on this from the Yocto/Bitbake core developers.

**Comment by OliverFendt** [comment]
@Jasper-Ben thank you for reaching out to Yocto to get a third opinion. 

As said I will work on the two mentioned packages. 
I also want to inform you, that I have currently some other packages in work, I will finish the "tag versions" of them and then check their "release versions" for differences. Just to let you know.
Once you have the third opinion, it would also be nice if you can provide the list of "release versions" which shall be available additionally to the "tag versions".

**Comment by Jasper-Ben** [comment]
@OliverFendt just to clearify: The two forementioned packages where just the two first packages I noticed this behaviour. Personally, I am not yet 100% convinced myself whether it is a good idea to add the release versions to the clearing files, since technically they are "build artifacts" from the configure script and not source code. Thus, I would suggest to resolve the principle debate first before jumping the gun and adding the release package clearing at this time. But of course, that decision is up to you.

**Comment by OliverFendt** [comment]
@Jasper-Ben  I agree, so we will decide on the further procedure once we have resolved the real need

**Comment by Jasper-Ben** [comment]
A quick update on this.

> Regarding your question, whether this should happen in a separate curation artifact or within the pre-existing curation IMO depends on whether there is the (the slightest) possibility of the configuration script modifying existing files. If this question can be confidently answered with "no", I do not see the harm of adding them into the existing curations.

Scratch this statement. Obviously, we cannot ensure that their haven't been changes made to files between the git source and the "release" package, as the content of the latter is completely up to the project maintainer. So if we at some point should decide that we need to curate releases as well, this would have to happen in a separate SPDX file. I don't know what I was thinking at that time :skull: 

> The "correct" fix in this case might also be that Yocto should use the "archive" instead of the "release" artifacts.

I have talked with some Yocto folks regarding whether it would make sense to replace release packages with either the git source (git fetcher) or with the GitHub source archive (the one you are currently using).

The short answer is: No.

For the following reasons:

Using the git fetcher: Git fetcher is significant slower and downloads more data than a release tarball

Using the GitHub source archive: The GitHub source archives are known to be non-deterministic, e.g. this case where GitHub repackaged existing git source archives, changing their file hashes and breaking various build systems in the process: https://lwn.net/Articles/921787/. Openembedded actually has a mechanism in place to verify that source code is **not** downloaded via the GitHub source archive links, exactly for this reason. (Luckily, my Osselot openembedded integration is not affected by this, as I do checksum matching on the individual extracted files, not the source archive as a whole.)

Thus, using the release package tarballs that are created by the software maintainers and not by GitHub is a valid use-case for openembedded (and other build systems).

---

So how do we move forward from this?

Regarding my openembedded integration (meta-osselot) I currently have two mechanisms for dealing with this (No. 2 is still in testing):

1. It is possible to create a source file ignore list on a per-package basis. Thus, in cases such as with libexpat where additional files are present that are not relevant from a license compliance perspective, these files can be added to the ignore list.
2. It is possible to define hash-equivalence relations for source code files on a per-package basis. Thus, if there is a hash-mismatch between a file within a release archive and the git archive, but this mismatch is not relevant from a license compliance perspective, one can define a hash-equivalence between these two files and solve the issue this way.

As a result there are only two cases left that cannot be solved within meta-osselot itself:

1. In the release package there are additional files that are relevant from a license compliance perspective.
2. There is a diff in a source file that is relevant from a license compliance perspective.

I am not sure to which extend this two cases are relevant. I would hope (and it would be reasonable to expect this from package developers) that there aren't differences between a release archive and a git source archive that are relevant from a license compliance perspective. I think it is safe to say, that would be a release packaging problem, **not** a Osselot problem. Thus, I would not spent time on solving these cases right now.

**Comment by OliverFendt** [comment]
@Jasper-Ben thank you very much for the investigations and your perspective on this. Given your conclusion (I fully agree with it), I will close the issue for the time being. It can be re-opened once there will be a need to do this.
