### ISSUE TITLE
Typos in download location and purl version

### ISSUE THREAD

**Issue by scanossmining** [Open-Source-Compliance/package-analysis#78]
I've noticed a few typos:

- libusb/version-1.0.26: hhttps instead of https, in the download location. Also, the version string inside the purl is missing the "v" from the original version name.
- flex/version-v2.6.4 : hhttps instead of https , in the download location.
- rauc - all versions: the version string inside the purl is missing the "v" from the original version name.
- react/version-18.2.0 - same as above, missing "v' in the purl version.

Do you accept PRs for these types of issues, should I create a pull request if I find any more of them or is it better to report them as issues?

**Comment by OliverFendt** [comment]
@scanossmining thank you very much for spotting the typos. Yes, I will accept PRs on that matter. Please go ahead and do a PR.

**Comment by OliverFendt** [comment]
fixed with PR #79 - so I will close the issue
