### ISSUE TITLE
tar.gz in package name

### ISSUE THREAD

**Issue by PatrickVog** [Open-Source-Compliance/package-analysis#82]
Hi all,

I was wondering why some *-OSS-disclosure.txt files have a .tar.gz ending. e.g. acl-2.3.1-OSS-disclosure.txt shows "acl-2.3.1.tar.gz" at the top. But other versions of acl just show acl-<version>. Is there a reason for this or is this just a bug. If so I would fix that.

BR
Patrick

**Comment by OliverFendt** [comment]
@PatrickVog thank very much you for spotting this. This is a relict, it would be great if you fix it

**Comment by PatrickVog** [comment]
Ok will create a PR then. 
While doing the modifications I figured out, that there are some files (or parts of them) with windows line endings. Should I also unify them?

**Comment by OliverFendt** [comment]
Great, yes unify them please.
